---
- name: add buster-backports
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main contrib non-free
    filename: buster-backports.list
  notify: update apt

# - name: Install Linux kernel headers
#   apt:
#     name: linux-headers-amd64
#   when: ansible_distribution == 'Debian'
  
- name: install wireguard
  apt:
    name: wireguard
    state: present

- name: check if a reboot is required after upgrade
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: reboot was needed
  reboot:
    reboot_timeout: 300
  when: reboot_required.stat.exists
